trigger:
  branches:
    include:
      - master  # Trigger builds from the master branch

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 5.x'

- task: NuGetCommand@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'

- task: VSBuild@1
  displayName: 'Build Solution'
  inputs:
    solution: '**/*.sln'
    msbuildArchitecture: 'x64'
    configuration: 'Release'

- task: VSTest@2
  displayName: 'Run Tests'
  inputs:
    platform: 'x64'
    configuration: 'Release'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
